server:
  port: 8081
spring:
  datasource:
    data-username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/relic
    type:


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
